### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by samuel-videau** [EinfachHans/cordova-plugin-advanced-imagepicker#1]
# Bug Report

**Current Behavior:**
When running the app and trying to open the imagePicker, I get this error : 

`E/Capacitor: Post message error:
    java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences)' on a null object reference
        at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
        at com.getcapacitor.MessageHandler.callCordovaPluginMethod(MessageHandler.java:107)
        at com.getcapacitor.MessageHandler.postMessage(MessageHandler.java:51)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:197)
        at android.os.HandlerThread.run(HandlerThread.java:67)`

I have no idea of what cause this error.

**Expected Behavior:**

**Steps to reproduce:**
Here is my code: 

`import AdvancedImagePicker from 'cordova-plugin-advanced-imagepicker';

selectImages(){

        AdvancedImagePicker.present({
            max: 10,
            asBase84: true
        }, (result) => {
            console.log(result);
        }, (error) => {
            console.error(error);
        });
}`

**Environment information:**

- Cordova CLI version 
	- `10.0.0`
- Cordova platform version
	- `Current working directory is not a Cordova-based project.`

It s on capacitor

- Plugins & versions installed in project (including this plugin)
    -same`
- Dev machine OS and version, e.g.
    - OSX
        - `sw_vers`
    - Windows 10
        - `1909`

**Comment by EinfachHans** [comment]
I haven't test this Plugin tomorrow, i will (probably tomorrow) abd come back to you. Thanks for using!

**Comment by EinfachHans** [comment]
Please tell my which Version of Capacitor you are using

**Comment by samuel-videau** [comment]
> Please tell my which Version of Capacitor you are using

Thanks ! I'm using Capacitor 2.4.0

**Comment by EinfachHans** [comment]
The Android Part is written in Kotlin - i'm very new to capacitor, did you specified anything for supporting kotlin?

**Comment by samuel-videau** [comment]
> The Android Part is written in Kotlin - i'm very new to capacitor, did you specified anything for supporting kotlin?

Nope, Capacitor is supposed so support Kotlin, i checked the files and I have this line :
`<preference name="GradlePluginKotlinEnabled" value="true"/>`

**Comment by EinfachHans** [comment]
Where do you add this, Capacitor has no `config.xml` right?

**Comment by samuel-videau** [comment]
> Where do you add this, Capacitor has no `config.xml` right?

My bad I don t have this line

**Comment by EinfachHans** [comment]
But you can build your app with it?

**Comment by samuel-videau** [comment]
> But you can build your app with it?

Yes I can , it's just when I call the function that I get this error

**Comment by EinfachHans** [comment]
Please provide a reproducable repo

**Comment by samuel-videau** [comment]
> Please provide a reproducable repo

I don't know what is a reproducable rep, but actually, if it's all the steps : 
-Create an ionic pj based on capacitor
- then run 'npm install cordova-plugin-advanced-imagepicker'
- Import and create the function as I did
- then run : 'ionic capacitor run', 
- then on my device when i'm trying to call the function, I get this : 

`V/Capacitor/Plugin: To native (Cordova plugin): callbackId: AdvancedImagePicker1654271859, service: AdvancedImagePicker, action: present, actionArgs: [{"max":10,"asBase84":true}]
W/System.err: java.lang.ClassNotFoundException: de.hanskrywaa.AdvancedImagePicker.AdvancedImagePicker
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at java.lang.Class.forName(Class.java:379)
W/System.err:     at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:489)
        at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:169)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
        at com.getcapacitor.MessageHandler.callCordovaPluginMethod(MessageHandler.java:107)
        at com.getcapacitor.MessageHandler.postMessage(MessageHandler.java:51)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:197)
        at android.os.HandlerThread.run(HandlerThread.java:67)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "de.hanskrywaa.AdvancedImagePicker.AdvancedImagePicker" on path: DexPathList[[zip file "/data/app/io.ionic.ceopulser-VqzUL-YPIr8jtuR13WftiQ==/base.apk"],nativeLibraryDirectories=[/data/app/io.ionic.ceopulser-VqzUL-YPIr8jtuR13WftiQ==/lib/arm64, /system/lib64]]
W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    	... 12 more
I/System.out: Error adding plugin de.hanskrywaa.AdvancedImagePicker.AdvancedImagePicker.
E/Capacitor: Post message error:
    java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences)' on a null object reference
        at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
        at com.getcapacitor.MessageHandler.callCordovaPluginMethod(MessageHandler.java:107)
        at com.getcapacitor.MessageHandler.postMessage(MessageHandler.java:51)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:197)
        at android.os.HandlerThread.run(HandlerThread.java:67)
D/InputMethodManager: HSIFW - flag : 0 Pid : 27769`

**Comment by EinfachHans** [comment]
Nope i can't build the Project in Android Studio like this.

You will need to create a repository which includes a small capacitor project incl. android folder, which i just can check out and run

**Comment by samuel-videau** [comment]
> Nope i can't build the Project in Android Studio like this.
> 
> You will need to create a repository which includes a small capacitor project incl. android folder, which i just can check out and run

I've created an other project to send you, but on this one I get a build error : 
`Could not find method buildFeatures() for arguments [build_ae6adermvbopyghsqz9h5hckh$_run_closure1$_closure2@2f25cd62] on object of type com.android.build.gradle.internal.dsl.BaseAppModuleExtension.`

The link of the depositorie : 

https://github.com/samuel-videau/testPicker

**Comment by EinfachHans** [comment]
I need a Repo which shows me the error you have, not another one. The one you have now can be resolved by changing all versions of `com.android.tools.build:gradle` to **4.0.1**

**Comment by samuel-videau** [comment]
> I need a Repo which shows me the error you have, not another one. The one you have now can be resolved by changing all versions of `com.android.tools.build:gradle` to **4.0.1**

Ok wait, i will copy the project I'm working on, and cut some parts

**Comment by samuel-videau** [comment]
Ok that's it : https://github.com/samuel-videau/testImagePicker

Run `npm install
ionic build
ionic capacitor run`

If you have build problems, try this:

`npx jetify
npx cap sync
ionic cap sync`

**Comment by EinfachHans** [comment]
in this repo my plugin isn't even added?

**Comment by samuel-videau** [comment]
> in this repo my plugin isn't even added?

It's supposed to be actually, on my project it is

**Comment by EinfachHans** [comment]
i can't see it in here: https://github.com/samuel-videau/testImagePicker/blob/master/package.json

**Comment by samuel-videau** [comment]
> i can't see it in here: https://github.com/samuel-videau/testImagePicker/blob/master/package.json

Indeed i saw my depo was not on date, sorry i m not really familiar with github, I m trying creating a new one and i let you know when I m done

**Comment by EinfachHans** [comment]
I don't know whats the error here. As #3 Capacitor seems to work 🤔
