### ISSUE TITLE
cannot install on ios since last update 

### ISSUE THREAD

**Issue by tempo-riz** [EinfachHans/cordova-plugin-advanced-imagepicker#49]
seems like a dependecy/versioning issue but plugin install fails :
**cordova plugin add cordova-plugin-advanced-imagepicker**

```
Installing "cordova-plugin-advanced-imagepicker" for ios
Plugin dependency "cordova-plugin-add-swift-support@2.0.2" already fetched, using that version.
Dependent plugin "cordova-plugin-add-swift-support" already installed on ios.
Running command: pod install --verbose
Failed to install 'cordova-plugin-advanced-imagepicker': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/thib/Desktop/app/node_modules/cordova-common/src/superspawn.js:136:25)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
pod: Command failed with exit code 1
```

**pod repo update**     

                                 
```
Updating spec repo `trunk`
Updating spec repo `yummypets-ypimagepicker`
```

**pod install**                                              
```
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "YPImagePicker":
  In Podfile:
    YPImagePicker (= 5.2.1)

Specs satisfying the `YPImagePicker (= 5.2.1)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by EinfachHans** [comment]
This version exists, so should ne a problem at your local pod setup: https://cocoapods.org/pods/YPImagePicker

**Comment by MaximBelov** [comment]
Add to config.xml
    <platform name="ios">
   ...
        <preference name="SwiftVersion" value="4.2" />
  ...

**Comment by Kersei** [comment]
I know this is an old thread but the way to fix this is to set your minimum deployment target to 12 as
`<platform name="ios"> ... <preference name="deployment-target" value="12" /> ...`

I'm just answering because I had the same issue and this was the first thing that shows in google

**Comment by Mr-Anonymous** [comment]
I have the same issue. I cannot install it and adding `<preference name="deployment-target" value="12.0" />` or `<preference name="SwiftVersion" value="4.2" />` or `<preference name="SwiftVersion" value="5.3" />` or anything makes a difference. 

```
% cordova plugin add cordova-plugin-advanced-imagepicker
Installing "cordova-plugin-advanced-imagepicker" for android
Subproject Path: CordovaLib
Subproject Path: app
Installing "cordova-plugin-advanced-imagepicker" for ios
Plugin dependency "cordova-plugin-add-swift-support@2.0.2" already fetched, using that version.
Dependent plugin "cordova-plugin-add-swift-support" already installed on ios.
Failed to install 'cordova-plugin-advanced-imagepicker': Error: Command failed with exit code 1: pod install --verbose
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-MyApp`: (``)

Finding Podfile changes
  A YPImagePicker

Resolving dependencies of `Podfile`
  CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: all_pods_versions_8_1_b.txt exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/8/1/b/YPImagePicker/5.2.2/YPImagePicker.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/8/1/b/YPImagePicker/5.2.1/YPImagePicker.podspec.json exists! Returning local because checking is only performed in repo update
[!] CocoaPods could not find compatible versions for pod "YPImagePicker":
  In Podfile:
    YPImagePicker (= 5.2.1)

Specs satisfying the `YPImagePicker (= 5.2.1)` dependency were found, but they required a higher minimum deployment target.

/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:317:in `raise_error_unless_state'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:299:in `block in unwind_for_conflict'
<internal:kernel>:90:in `tap'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `unwind_for_conflict'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:682:in `attempt_to_activate'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/resolver.rb:94:in `resolve'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/installer/analyzer.rb:1082:in `block in resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/installer/analyzer.rb:1080:in `resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/installer/analyzer.rb:125:in `analyze'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/installer.rb:422:in `analyze'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/installer.rb:162:in `install!'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/command/install.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/bin/pod:55:in `<top (required)>'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/bin/pod:25:in `load'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/bin/pod:25:in `<main>'
    at makeError (/Users/me/Sites/MyApp-Production/MyApp-mobile/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/me/Sites/MyApp-Production/MyApp-mobile/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Command failed with exit code 1: pod install --verbose
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-MyApp`: (``)

Finding Podfile changes
  A YPImagePicker

Resolving dependencies of `Podfile`
  CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: all_pods_versions_8_1_b.txt exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/8/1/b/YPImagePicker/5.2.2/YPImagePicker.podspec.json exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/8/1/b/YPImagePicker/5.2.1/YPImagePicker.podspec.json exists! Returning local because checking is only performed in repo update
[!] CocoaPods could not find compatible versions for pod "YPImagePicker":
  In Podfile:
    YPImagePicker (= 5.2.1)

Specs satisfying the `YPImagePicker (= 5.2.1)` dependency were found, but they required a higher minimum deployment target.

/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:317:in `raise_error_unless_state'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:299:in `block in unwind_for_conflict'
<internal:kernel>:90:in `tap'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `unwind_for_conflict'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:682:in `attempt_to_activate'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/resolver.rb:94:in `resolve'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/installer/analyzer.rb:1082:in `block in resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/installer/analyzer.rb:1080:in `resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/installer/analyzer.rb:125:in `analyze'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/installer.rb:422:in `analyze'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/installer.rb:162:in `install!'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/command/install.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/bin/pod:55:in `<top (required)>'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/bin/pod:25:in `load'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/bin/pod:25:in `<main>'
```

**Comment by Mr-Anonymous** [comment]
Why was this closed? This issue is not addressed.

**Comment by tempo-riz** [comment]
I created this issue on Sep 5, 2022 and the old answers didn't help you, I think in your own interest creating a new issue might be better.
